# Wink
language: python
python:
  - 2.7
env:
  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.

  ## Out of tree builds (default):
  # Debug build
  - BUILD_TYPE="Debug"
  # Debug build (with BFD and CSYMPY_ASSERT)
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_ASSERT="yes"
  # Debug build (with BFD and CSYMPY_ASSERT and CSYMPY_THREAD_SAFE)
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_ASSERT="yes" WITH_CSYMPY_THREAD_SAFE="yes"
  # Debug build (with BFD and CSYMPY_ASSERT) with ECM
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_ASSERT="yes" WITH_ECM="yes"
  # Debug build (with BFD and CSYMPY_ASSERT) with PRIMESIEVE
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_ASSERT="yes" WITH_PRIMESIEVE="yes"
  # Debug build (with BFD and CSYMPY_ASSERT) with Python 2.7
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_ASSERT="yes" WITH_PYTHON="yes"
  # Debug build (with BFD and CSYMPY_ASSERT) with Arb
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_ASSERT="yes" WITH_ARB="yes"
  # Debug build with Teuchos::RCP (just to test that it compiles)
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_RCP="no"
  # Release build (with BFD)
  - WITH_BFD="yes"

  ## In-tree builds (we just check a few configurations to make sure they work):
  # Debug build without Python:
  - BUILD_TYPE="Debug" WITH_BFD="yes" TEST_IN_TREE="yes"
  # Debug build with Python 2.7:
  - BUILD_TYPE="Debug" WITH_BFD="yes" TEST_IN_TREE="yes" WITH_PYTHON="yes" WITH_CSYMPY_ASSERT="yes"
  # Release build with Python 2.7:
  - TEST_IN_TREE="yes" WITH_PYTHON="yes"
matrix:
  include:
    # These test the default Release build with other Python versions
    - python: 2.6
      env:
        - WITH_PYTHON="yes"
    - python: 3.2
      env:
        - WITH_PYTHON="yes"
    - python: 3.3
      env:
        - WITH_PYTHON="yes"
    - python: 3.4
      env:
        - WITH_PYTHON="yes"
    # These test the setup.py file
    - python: 2.6
      env:
        - TEST_IN_TREE="yes" PYTHON_INSTALL="yes"
    - python: 2.7
      env:
        - TEST_IN_TREE="yes" PYTHON_INSTALL="yes"
    - python: 3.2
      env:
        - TEST_IN_TREE="yes" PYTHON_INSTALL="yes"
    - python: 3.3
      env:
        - TEST_IN_TREE="yes" PYTHON_INSTALL="yes"
    - python: 3.4
      env:
        - TEST_IN_TREE="yes" PYTHON_INSTALL="yes"
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libgmp-dev
  - if [[ "${WITH_BFD}" == "yes" ]]; then
        sudo apt-get install binutils-dev;
    fi
  - if [[ "${WITH_ECM}" == "yes" ]]; then
        sudo apt-get install libecm-dev;
    fi
  - if [[ "${WITH_PRIMESIEVE}" == "yes" ]]; then
        wget http://dl.bintray.com/kimwalisch/primesieve/primesieve-5.2.tar.gz;
        tar -xzf primesieve-5.2.tar.gz;
        cd primesieve-5.2 && ./configure && make && sudo make install && cd ..;
    fi
  - if [[ "${WITH_ARB}" == "yes" ]]; then
        sudo apt-get install libmpfr-dev;
        wget http://www.flintlib.org/flint-2.4.4.tar.gz;
        tar -xzf flint-2.4.4.tar.gz;
        cd flint-2.4.4 && ./configure && make && sudo make install && cd ..;
        wget https://github.com/fredrik-johansson/arb/archive/2.2.0.tar.gz;
        tar -xzf 2.2.0.tar.gz;
        cd arb-2.2.0 && ./configure && make ARB_GMP_LIB_DIR=/usr/lib/x86_64-linux-gnu ARB_MPFR_LIB_DIR=/usr/lib/x86_64-linux-gnu && sudo make ARB_GMP_LIB_DIR=/usr/lib/x86_64-linux-gnu ARB_MPFR_LIB_DIR=/usr/lib/x86_64-linux-gnu install && cd ..;
    fi
install:
  - if [[ "${WITH_PYTHON}" == "yes" ]] || [[ "${PYTHON_INSTALL}" == "yes" ]]; then
        pip install --install-option="--no-cython-compile" cython;
        pip install sympy;
    fi
script:
  - bin/test_travis.sh
notifications:
  email: false
